name: self-hosted-runner

on: 
   workflow_dispatch:

jobs:
  self-hosted:
      runs-on: my-linux-runner
      steps: 
        - name: checkout
          uses: actions/checkout@v4
        
        - name: self-hosted-runner-hostname
          run: hostname
          
        - name: print working directory
          run: pwd
          
        - name: Create Test File
          run: | 
           echo "Hello from self-hosted runner" > test-file.txt

        - name: list files
          run: ls -la 
